version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.6.0
    steps:
      - run:
          name: "Set ISHIKO_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/ishiko/cpp && echo 'export ISHIKO_CPP_ROOT="/workspace/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/ishiko/cpp/synchronization
      - run:
          name: "Build: Ishiko/C++ Synchronization"
          command: cd /projects/ishiko/cpp/synchronization/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
